# Generated by Django 4.0.6 on 2022-08-18 21:31

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogo', '0002_enfoque_valores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.areaasesoria')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asesoria_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asesoria_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('codigo', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('modalidad', models.CharField(choices=[('Regular', 'Regular'), ('Multigrado', 'Multigrado')], default='Regular', max_length=50)),
                ('dependencia', models.CharField(choices=[('Pública', 'Pública'), ('Subvencionada', 'Subvencionada')], default='Pública', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.ciudad')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='escuela_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='escuela_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('duracion', models.DurationField()),
                ('modalidad_visita', models.CharField(choices=[('Presencial', 'Presencial'), ('Remota', 'Remota')], default='Presencial', max_length=50)),
                ('comentarios', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asesoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visita.asesoria')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='visita_created_by', to=settings.AUTH_USER_MODEL)),
                ('tipo_visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.tipovisita')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='visita_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('codigo', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=14)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('telefono', models.PositiveIntegerField(blank=True, null=True)),
                ('grados_asign', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, '1ro'), (2, '2do'), (3, '3ro'), (4, '4to'), (5, '5to'), (6, '6to'), (7, '7mo'), (8, '8vo'), (9, '9no'), (10, '10mo'), (11, '11mo')]), size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='profesor_created_by', to=settings.AUTH_USER_MODEL)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visita.escuela')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='profesor_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
