# Generated by Django 4.0.6 on 2022-08-18 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogo', '0002_enfoque_valores'),
        ('visita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='detalle_enfoques_created_by', to=settings.AUTH_USER_MODEL)),
                ('enfoque', models.ManyToManyField(to='catalogo.enfoque')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visita.profesor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='detalle_enfoques_updated_by', to=settings.AUTH_USER_MODEL)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visita.visita')),
            ],
        ),
    ]
