# Generated by Django 4.0.6 on 2022-08-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0002_detalleprofesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='profesor',
            field=models.ManyToManyField(through='visita.DetalleProfesor', to='visita.profesor'),
        ),
    ]
