# Generated by Django 4.0.6 on 2022-09-06 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0003_visita_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='escuela',
            field=models.ForeignKey(default=15158, on_delete=django.db.models.deletion.CASCADE, to='visita.escuela'),
            preserve_default=False,
        ),
    ]
